name: Matrix Testing
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest  
    strategy:
      matrix:
        configuration: [debug, release, scan]
        env: [dev,test,uat,ppe,prod]
    steps:
    - run: echo "This job builds the cofiguration ${{ matrix.configuration}}."
